//
//  ViewController.m
//  Face Scanner
//
//  Created by Georges Kanaan on 3/23/15.
//  Copyright (c) 2015 Georges Kanaan. All rights reserved.
//

#import "ViewController.h"

#import <CoreImage/CoreImage.h>

#import "KairosSDK.h"
#import "UIImage+FaceDetection.h"
#import "FaceSelectionCollectionViewController.h"

@interface ViewController () <UINavigationControllerDelegate, UIImagePickerControllerDelegate, UIActionSheetDelegate> {
  UIImagePickerController *imagePicker;
}

@property (strong, nonatomic) IBOutlet UILabel *statusLabel;
@property (strong, nonatomic) IBOutlet UIImageView *selectedFaceImageView;
@property (strong, nonatomic) IBOutlet UIImageView *recognizedFaceImageView;

@end

@implementation ViewController

static NSString * const galleryIdentifier = @"studentGallery";

- (void)viewDidLoad {
  [super viewDidLoad];
  // Do any additional setup after loading the view, typically from a nib.
  
  //update status bar appearance
  [self setNeedsStatusBarAppearanceUpdate];
  
  //authenticate with Kairos
  [KairosSDK initWithAppId:@"77ccfe89" appKey:@"03eed3cb0d74e95dc34e6e14cd1a2fbc"];
  
  //enroll all students
  if (![[NSUserDefaults standardUserDefaults] boolForKey:@"enrolledStudents"]) [self enrollEntireStudentDatabase];
  
  //init the UIImagePickerController
  imagePicker = [UIImagePickerController new];
  imagePicker.allowsEditing = YES;
  imagePicker.delegate = self;
}

- (void)didReceiveMemoryWarning {
  [super didReceiveMemoryWarning];
  // Dispose of any resources that can be recreated.
}

#pragma mark - Face Recognition
- (void)recognizeFace:(UIImage *)selectedFace {
  //update UI
  [self.statusLabel setText:@"Uploading face to server for recognition..."];
  [self.selectedFaceImageView setImage:selectedFace];
  
  //upload image to kairos for recognition
  [KairosSDK recognizeWithImage:selectedFace threshold:@".80" galleryName:galleryIdentifier maxResults:@"1" success:^(NSDictionary *response) {
    NSLog(@"response: %@",response);
    
    [self.statusLabel setText:@"Processing results..."];
    
    NSString *status = [[[[response objectForKey:@"images"] objectAtIndex:0] objectForKey:@"transaction"] objectForKey:@"status"];
    if ([status isEqualToString:@"failure"]) {
      [self.statusLabel setText:@"No match found"];
    }
    
  } failure:^(NSDictionary *response) {
    [self.statusLabel setText:@"Failed to recognize face"];
  }];
}

#pragma mark - Enrolling Student Database
- (NSArray*)studentNames {
  return @[
           @"George Hanna",
           @"Walid Matta",
           @"Diana Abou Lebdeh",
           @"Mimoza Arawi",
           @"Paula Mufarrij",
           @"Wadad Hoss",
           @"Riad Chirazi",
           @"Ryan Wilson",
           @"Raymond Azar",
           @"Jad-Elie Chamoun",
           @"Mary-Anne Derkaloustian",
           @"Anthony Halalel",
           @"Natalie Halalel",
           @"Anthony-Brian Hanna",
           @"Sarah Mansour",
           @"Alexandre Melki",
           @"Emile Murr",
           @"Joseph Naaman",
           @"Nicole Samaha",
           @"Nicolas Saber",
           @"Aya-Layl Torbey",
           @"Lea Zayek",
           @"Roy-Dory Abisaad",
           @"Caren Abitarabay",
           @"Yasmina Abusamra",
           @"Aya Akl",
           @"Ghadi Azour",
           @"Omar Bassil",
           @"Philippe Bouhabib",
           @"Christopher Chammas",
           @"Adnan Hazim",
           @"Rayan Hobaybel",
           @"Nassif Jabbour",
           @"Nour Karam",
           @"Paolo Kasbani",
           @"Joe-Daher Kehdy",
           @"Malek Khouryel",
           @"Raya Laoun",
           @"Carine Mardelli",
           @"Maria Matta",
           @"Marc Oueiss",
           @"Tracy Rahi El",
           @"Kareem Rizk",
           @"Christina Youssef",
           @"Nicole-Karen Abisaad",
           @"Hala Ariss",
           @"Rodolphe Baladi",
           @"Andrew-Elias Baroudi",
           @"Marc Baroudi",
           @"Karim Bekdash",
           @"Jaymee Chedrawi-Laba",
           @"Lea Fathallah",
           @"Raissa-Maria Fayad",
           @"Aya-Maria Goraeib",
           @"Nehme-Christian Khoury",
           @"Victor Khoury",
           @"Nour Moussa",
           @"Christophe Rizk",
           @"Michael Romanos",
           @"Antoine Semaan",
           @"Fouad Zoghbi",
           @"Elise Zogheib",
           @"Ryan Abdallah",
           @"Karl Abi Fadel",
           @"Joseph Abi Karam",
           @"Kevin-Joe Abi Raad",
           @"Julie Abou Kasm",
           @"Ghazal Altoun",
           @"Naia Ariss",
           @"Georges Asfahani",
           @"Georges Asmar El",
           @"Mazen Attie",
           @"Yendi Azar",
           @"Ara-John Baitarian",
           @"Haig-Alec Baitarian",
           @"Aya Baroudi",
           @"Marie-Jeanne Baroudi",
           @"Sami Bayoud",
           @"Carla Boulos",
           @"Kiyana-Teresa Cavalcanti",
           @"Andrea-Maria Corban",
           @"Violette Daaboul",
           @"Nour Dahdah El",
           @"Alexandre Dahrouge",
           @"Gary Debbas",
           @"Maria Debs",
           @"Philippe Delifer",
           @"Armand Djizmeian",
           @"Laetitia Doumet",
           @"Linda Emad",
           @"Elie Estephan",
           @"Milana Farah",
           @"Nicolas Farah",
           @"Nour Eliane Farhat",
           @"Salma Feghali",
           @"Karim-Christian Ghanem",
           @"Alexandre Ghawi El",
           @"Leeza-Maria Ghawi El",
           @"Peter Gholam",
           @"Mikael Haddad El",
           @"Elena Hafez",
           @"Makram Halabi",
           @"Nour Halabi",
           @"Riwa Hanna",
           @"Anna-Maria Hayek",
           @"Alicia-Mary Iskandarian",
           @"Joe Jreissati",
           @"Nour Karkabi",
           @"Thea Kassabian",
           @"Catherine Kebbe",
           @"Nour Kehdy",
           @"Georges Khalil",
           @"Jad Khoury",
           @"Nicolas Khoury",
           @"Jade Klat",
           @"Thomas Komen",
           @"Leticia Sarin Koundakjian",
           @"Marc Matta",
           @"Dany Mazegi",
           @"Ekira Merhej",
           @"Nabih-Gabriel Mouawad",
           @"Carina Moujaes",
           @"Elias Nahra",
           @"Antoine Nassif",
           @"Michel Noumair",
           @"Mark-Antoine Raphael",
           @"Elias Rebeiz",
           @"Serena Rizk",
           @"Joseph Roustom",
           @"Noor Saade",
           @"Waleed Saade",
           @"Emile Saliba",
           @"Rita Saliba",
           @"Catherine Shebaya",
           @"Riad Tahan",
           @"Patrick Tufenkjian",
           @"Dana Tunisi Al",
           @"Julian Vanlian",
           @"Chloe Yamine",
           @"Edwin Yessayan",
           @"Chloe Maria Zacca",
           @"Assaad Zayek",
           @"Sara Abi Fadel",
           @"Nai-Christie Abou Chahla",
           @"Ray Abou Karam",
           @"Marianne Abou Zeid",
           @"Shaun Agostine",
           @"Alexandros Apostolopoulos",
           @"Maurice Ayoub",
           @"Anthony Azour",
           @"Mayssa Bamehriz",
           @"Maria Bou Samra",
           @"Mario Assaad BouZakhm",
           @"Kevin Chabab",
           @"Karl Chammas",
           @"Rita Chammas",
           @"Edward Chidiac",
           @"Anthony Diab",
           @"Yasmina EphramBoustani",
           @"Raoul Fathallah",
           @"Tara Flouty",
           @"Alessandra Gargour",
           @"Sherif-Michel Ghali",
           @"Andrea Ghattas",
           @"Dimitri Gholam",
           @"Mayssa Goraeib",
           @"Joy Habib",
           @"Dylan Haddad",
           @"Michael Haddad",
           @"Marya Hadife",
           @"Youssef Hakim",
           @"Edward Hanna",
           @"Lea Harb",
           @"Celia Hitti",
           @"Erica Jabbour",
           @"Laura Jahchan",
           @"Nayla Karam",
           @"Charles Bachir Khalaf",
           @"Malek Khalil El",
           @"Jay Khoury Awad",
           @"Jose Khoury",
           @"Raffaella Khoury",
           @"Rhea Khoury",
           @"Maria Kodeih",
           @"Tiana Lori Koundakjian",
           @"Tia Manoukian",
           @"Ivana Maria Mansour",
           @"Aya Moujaes",
           @"Joseph Nassif",
           @"Chloe Nini",
           @"Marc Njeim",
           @"Lynn Noufaily",
           @"Ralph Oueiss",
           @"Souheil Rajeh",
           @"Riwa Rida",
           @"Christian Rizk",
           @"Michele Rizk",
           @"Christina Romanos",
           @"Tiffany Saade",
           @"Emma-Maria Sader",
           @"Alexandre Saliba",
           @"Tayma Saliba",
           @"Joan Saniour",
           @"Cathaline Sarkis",
           @"Jeremy Daniel Sebaaly",
           @"Karl Stephan",
           @"Yasmine Tohme",
           @"Alex Tufenkjian",
           @"Celine Younes",
           @"Karim Abboud",
           @"Chaya Atallah",
           @"Georges Atallah",
           @"Marc George Baroudi",
           @"Jeremy Bechara",
           @"Daniel Beylerian",
           @"Khaled Bouchebel",
           @"Yara Chamaa",
           @"Karen Chammas",
           @"Yasmina Chemayaa",
           @"Chad Debbas",
           @"Anthony Eid",
           @"Maissa Eid",
           @"Marc Eid",
           @"Cindy-Rose Farhat",
           @"Kyann Hadife",
           @"Samer Hanna",
           @"Aya HawaEl",
           @"Nour Kanaan",
           @"Talya Kassabian",
           @"Alec Khatchadourian",
           @"Rhea Khazen El",
           @"Anthony Matar",
           @"Robert Mendelek",
           @"Georges Nader",
           @"Mia Naja",
           @"Maria Nohra",
           @"Maria Paoli",
           @"Roberto Rahal",
           @"Sacha Raphael",
           @"Tatiana Rebeiz",
           @"Jack Saniour",
           @"Lea Saroufim",
           @"Gabriel Shammas",
           @"Tarek Tohme",
           @"Rhea-Maria Tufenkjian",
           @"Laetitia Tyan",
           @"Alexandre Peter Yaverian",
           @"Mariam Younes",
           @"Tamara Zard Abou Jaoude",
           @"Luna Agostine",
           @"Kareem Azar",
           @"Louay Assaad (El)",
           @"Arlette Akl",
           @"Arlette Tabet",
           @"Carole Obeid",
           @"Claudine Makhoul",
           @"Daniele Bejjani",
           @"Elias Abdel Jalil",
           @"Elias Aswad",
           @"Edith Matta",
           @"Georgette Francis",
           @"Hoda Baaklini",
           @"Hyam Bou Matar",
           @"Jaana Lundholm",
           @"Jalal Souhaid",
           @"Loulou Abdel Ahad",
           @"Leila Kobeissy",
           @"Lydia Salame",
           @"Lara Wehbe",
           @"Myriam Bouzakhm",
           @"Mary-Helen Gholam",
           @"Maya Karam",
           @"Maya Tabbara",
           @"Nawal Haddad",
           @"Nivart Hakimian",
           @"Nabil Haddad",
           @"Marie Rose Abi Rached",
           @"Samar Tohme",
           @"Tania Sawaya",
           @"Wissam Hanna",
           @"Youssef Bou Abdo",
           @"Katia Aranji",
           @"Hiba Zaklit",
           @"Kinda Constantine",
           @"Robert P. Howe",
           @"Lara Kmeid",
           @"Ama Tabet",
           @"ChristinaRita Accad",
           @"Johanna Asfour",
           @"Hazem Barake",
           @"Maya Bayoud",
           @"Mohamad Chahin",
           @"Sarah Hamasni",
           @"Nader Jaafar",
           @"Nassar Jarmakani",
           @"Jad Jawad",
           @"Lea Kabbani",
           @"Lea Khattab",
           @"Dalia Maktabi",
           @"Abdullah Masri Chaarani",
           @"Nathalie Raffoul",
           @"Lana Shamkhani",
           @"Reem Succarie",
           @"Karim Zein",
           @"Sarah Baalbaki",
           @"Karim Ezzeddine",
           @"Afif Fakhreddine",
           @"KarenDonna Ghawi",
           @"Nour Hachache",
           @"Dana Hamam",
           @"Rand Hilal",
           @"Yasmin Hussein Mansour",
           @"Tamer Jaber",
           @"Yara Jaber",
           @"Sara Jamil",
           @"Sam Kaddouh",
           @"Mohamad Kassem",
           @"Kareem Oueini",
           @"Sandra Rafii",
           @"Fouad Sheikh",
           @"Jad Soubra",
           @"Basil Toufeili",
           @"Ziad Zein",
           @"JadJulien Arabi",
           @"Rami Beyhum",
           @"Tarek Cheaito",
           @"Mohamad Dakik",
           @"Karim Domiati",
           @"Haya Doughan",
           @"Ramzi Fathallah",
           @"Jude Haddad",
           @"Dima Hajj",
           @"Karim Hamadeh",
           @"Jad Harake",
           @"Serene Hassouna",
           @"Aya Hout",
           @"Ibrahim Ibrahim",
           @"Aya Itani",
           @"Rena Kobeissi",
           @"KarenGhia Mukalled",
           @"Majd Ouri",
           @"Laya Rifai",
           @"Jad Tawil",
           @"Ehab Bou Ayash",
           @"Tania Chaib",
           @"Sinan Faiad",
           @"Sari Habre",
           @"Adam Hallab",
           @"Noor Harajli",
           @"Ali Hubballah",
           @"MohamadAdnan Itani",
           @"Yara Itani",
           @"Tarek Korek",
           @"AbdelRahman Masri",
           @"Najwa Mourad",
           @"Malek Shehab",
           @"Ali Soufan",
           @"Kamar Taher Fadlallah",
           @"Suha Zreik",
           @"Youssef Haidar",
           @"Jalal Ladki",
           @"Ammar AbouHamzeh",
           @"Rayan Sinno",
           @"Nour Alami",
           @"Talal Ammache",
           @"Alia Assaad",
           @"TinaMaria Barbir",
           @"Selena Bouris",
           @"LeaLina Chawa",
           @"Patrick Comair",
           @"SarahMichelle Cortas",
           @"Sarah Debbas",
           @"Karim Fakhoury",
           @"Aya Ghandour",
           @"Karim Hassan",
           @"Tamara Haydar",
           @"Karim Ibrahim",
           @"Dany Jammal",
           @"Nael Khalil",
           @"Yasmina Khazen",
           @"Nour Merhebi",
           @"Ali Osman",
           @"Mira Safieddine",
           @"Ward Salman",
           @"Nadine Shaker",
           @"Maha Solh",
           @"AnabelleMaria Abdallah",
           @"Tamara AbouHamzeh",
           @"Mohammad Assaad",
           @"Yasmina Bsat",
           @"Judy Charamand",
           @"Celine Daher",
           @"Omar Dandan",
           @"Maram Jammal",
           @"Lynn Kaddoura",
           @"AbdelMajid Kalo",
           @"Nadim Kanazi",
           @"Hassan Mansour",
           @"Alexander Nassar",
           @"Tamara Raad",
           @"Hamza Saad",
           @"Ali Safieddine",
           @"Youssef Sayed",
           @"John Shaib",
           @"Sarah Sharif",
           @"Carmen Uwaydah",
           @"Razane Wehbe",
           @"AbdelMonem Youssef",
           @"Noor ZeinEl",
           @"Omar Anouti",
           @"Mourad Ariss",
           @"Samir Ayass",
           @"Omar Baghdadi",
           @"Mohammad Baker",
           @"Lara Barrage",
           @"Osmat Bekdache",
           @"Celine Dajani",
           @"Celine Dib",
           @"Jad Dirani",
           @"Zein Idriss",
           @"Ali Ismail",
           @"Rawad Lakkis",
           @"Sabine Mirza",
           @"Mouin Mounzer",
           @"Atef Nsouli",
           @"Sondos Osman",
           @"Rasha Sahili",
           @"Ryan Sawaya",
           @"MohBahjat Serhal",
           @"Lea Sleiman",
           @"Bilal Tarabishi",
           @"Tatiana Wazzan",
           @"Naim Zgheib",
           @"Edward Akkawi",
           @"Marwan Bounassif",
           @"Christopher Faddoul",
           @"Ryan Haddad",
           @"Bassam Mitri",
           @"Giorgio Saade",
           @"Rami-Joe Najd",
           @"Malek Sadi",
           @"Jad-Baptist Bounassif",
           @"Mohamed-Ali MawlaAl",
           @"Rudy Sayegh",
           @"Alexander Ziade",
           @"Victor Acra",
           @"Thalia Rita Bou Malhab",
           @"Charles Malik",
           @"Maria Mansour",
           @"Christopher Minassian",
           @"Mia Saade",
           @"Alexandra Sayegh",
           @"Mark Yeretzian",
           @"Nabil Abdallah",
           @"Yves Achdjian",
           @"Sarah Akkawi",
           @"Talal Alaeddine",
           @"Leila Balaa",
           @"Giorgio Barakat",
           @"Lea Fakhir",
           @"Tammy Gebara",
           @"David Mansour",
           @"Marc Racoubian",
           @"Khalil Sayegh",
           @"Eliot Haddad",
           @"Lilas Abdel khalek",
           @"Salah Aboulkhoudoud",
           @"Lea Abu Musa",
           @"Firas Achi El",
           @"Wafi Achi El",
           @"Ahmad Achour",
           @"Jad Alami",
           @"Wafic Alayli",
           @"Samir Ali Hassan",
           @"Nayef Amhaz",
           @"Abdallah Amin Al",
           @"Ahmad Arab Al",
           @"Mia Arakji",
           @"Nour Arakji",
           @"Karl Patrick Arkhondis",
           @"Raja Asfour",
           @"Nadim Ataya",
           @"Rafi Attar",
           @"Anna Bachour",
           @"Rima Baker",
           @"John Baroudi",
           @"Jad Barrage",
           @"Jad Bdeir",
           @"Lea Bdeir",
           @"Makram Bekdache",
           @"Lea Berry",
           @"Lynn Berry",
           @"Lana Beydoun",
           @"Youmna Bissat",
           @"Nadim Chahine",
           @"Karim Chaitani",
           @"Yara Jasmine Chami",
           @"Leen Chanouha",
           @"Wahib Charamand",
           @"George Chatila",
           @"Majd Chedid",
           @"Mohamad Chehab",
           @"Anthony Chikhani El",
           @"Maria Chikhani El",
           @"Dounia Choucair",
           @"Yahya Johnny Dabbagh",
           @"Amir Dagher",
           @"Karim Damerji",
           @"Karim Daouk",
           @"Karim Daouk",
           @"Riwa Dbouk",
           @"Serene Dbouk",
           @"Mustapha Leith Dernaika",
           @"Yasmine Dib",
           @"Nada Doughan",
           @"Yara Doumani",
           @"Jad Eid",
           @"Malek Ejjeh",
           @"Raya Fakhreddine",
           @"Petra Yasmine Fallaha",
           @"Hana Farchoukh",
           @"Zaki Fawaz",
           @"Jad Gerges",
           @"Aya Eve Ghutmi",
           @"Armen Hadjinian",
           @"Rita Hage",
           @"Hussam Haidar",
           @"Talia Hakim El",
           @"Rayan Hamdan",
           @"Maria Hanna",
           @"Celine Hobeichi",
           @"Sara Horr El",
           @"Wael Houssami",
           @"Anwar Hussein Agha",
           @"Karim Husseini El",
           @"Rawad Ibrahim",
           @"Jad Idriss",
           @"Roy Inkidar",
           @"Judy Issa",
           @"Dima Itani",
           @"Lana Itani",
           @"Lea Itani",
           @"Nadim Itani",
           @"Yahya Itani",
           @"Yasmina Itani",
           @"Mariam Jabakhanji",
           @"Saria Jamil",
           @"Maya Jaroudi",
           @"Meera Jawhar",
           @"Aya Kabbani",
           @"Sama Kaddouh",
           @"Adel Kadi El",
           @"Yasmina Kalakish",
           @"Omar Kandil",
           @"Thalia Kayal",
           @"Ahmad Khateeb Al",
           @"Tarek Khatib",
           @"Hana Khayat El",
           @"Aya Kodeih",
           @"Mohamad Kreidieh",
           @"Jad Mahfouz",
           @"Jana Mahfouz",
           @"Karim Mahfouz",
           @"Yasmeena Makhzoumi",
           @"Karen Maktabi",
           @"Reina Maktabi",
           @"Jean Mattar",
           @"Racha Mawla El",
           @"Jimmy Mehanna",
           @"Emesa Melki",
           @"Malak Mikdashi",
           @"Marla Mirza",
           @"Moh.Omar Mkhallati",
           @"Yara Mneimneh",
           @"Enora Mohsen",
           @"Zane Mroue",
           @"Mia Nahas",
           @"Ayoub Naim",
           @"Tamer Nakfour",
           @"Nicole Nakhle",
           @"Emily Venus Nassar",
           @"Lana Nassar",
           @"Issa Nouh",
           @"Yasmin Noureddine",
           @"Elias Aleksander Skulte Ouaiss",
           @"Omar Oud El",
           @"Mohamad Atef Oueidat",
           @"Omar Rabaa Al",
           @"Aya Rai",
           @"Ahmad Ramadan",
           @"Rhaya Rassi El",
           @"Yasmina Saad",
           @"Mohammad Omar Saade",
           @"Tarek Sahyoun",
           @"Eva Sakr",
           @"Talia Sakr",
           @"Talal Salman",
           @"Marc Samra",
           @"Ahmad Seoudi El",
           @"Karim Shatila",
           @"Samir Shemaitelly",
           @"Rayan Sidani El",
           @"Sym Sidani",
           @"Patrick Skaf",
           @"Mohammad Soufan",
           @"Kamal Tabsh Al",
           @"Halima Taddei",
           @"Tiffany Tawil El",
           @"Marwan Uwaydah",
           @"Andrew Yazbek",
           @"Joseph Yazbek",
           @"Lana Younes",
           @"Yasmine Zeidan",
           @"Yara Zgheib",
           @"Lynn Abdel Baki",
           @"Jude Abiad",
           @"Vivian Aboulmouna",
           @"Jad Abs",
           @"Haya Amin Al",
           @"Tarek Ammar",
           @"Mia Araji",
           @"Reina Aris",
           @"Patricia Arkhondis",
           @"Lana Assaad El",
           @"Seif El Dine Attoue",
           @"Omar Baalbaki",
           @"Roya Baalbaki",
           @"Walid Baghdadi El",
           @"Gida Barazi Al",
           @"Yasmina Bayoud",
           @"Jad Beydoun",
           @"Yasmine Blanford",
           @"Yulia Boulos",
           @"Mayya Boury",
           @"Jamal Boustani",
           @"Lea Chahda",
           @"Adam Chahine",
           @"Ahmad Chamli",
           @"Raed Cheaito",
           @"Erik Bechara Dahan",
           @"Layla Daher",
           @"Malek Daher",
           @"Hiba Dakik",
           @"Sania Dandan",
           @"Sam Daou",
           @"Antoine Debbas",
           @"Nadim Dib",
           @"Marc Edde",
           @"Maya Ezzeddine",
           @"Mohammad Ezzeddine",
           @"Talal Fakhoury",
           @"Hassan Fawaz",
           @"Abdul Hamid Fil El",
           @"Lea Ftouni",
           @"Nour Gedeon",
           @"Karim Ghandour",
           @"Celine Ghoul El",
           @"Yacoub Haddad",
           @"Maher Haidar",
           @"Rama Hakim Al",
           @"Sara Halabi Hakim",
           @"Nadim Hamadeh",
           @"Leila Hammoud",
           @"Marya Hamoui",
           @"Dana Harake",
           @"Nadim Harake",
           @"Bassem Hardan",
           @"Mia Hilal",
           @"Issam Hoss El",
           @"Tamar Houri",
           @"Ali Husseini El",
           @"Jad Ibrahim",
           @"Lea Ibrahim",
           @"Danny Ibrahim-Basha",
           @"Yasmine Idriss",
           @"Tamara Inkidar",
           @"Serena Isaac",
           @"Ghia Ismail",
           @"Lara Itani",
           @"Taha Itani",
           @"Zeina Jaber",
           @"Wafic Jammal Al",
           @"Lana Kamareddine",
           @"Yara Kanaan",
           @"Bassel Kassak",
           @"Malek Kassak",
           @"Karim Kasti",
           @"Adel Katergi",
           @"Nadim Kattan",
           @"Rami Kfouri",
           @"Layan Khaled",
           @"Alexander Khalifa",
           @"Leah Khalifeh",
           @"Shafik Khalili",
           @"Wajih Khatib",
           @"Yehya Khattab",
           @"Omar Khayat El",
           @"Loulwa Khodr",
           @"Farid Khuri-Makdisi",
           @"Yasmina Kobeissi",
           @"Karim Kotob",
           @"Nasser Mahmasani Al",
           @"Lea Majed",
           @"Lynn Makarem",
           @"May Makhzoumi",
           @"Gady Makki",
           @"Karim Makki",
           @"Karim Mansour",
           @"Sara Mardini",
           @"Jad Mattar",
           @"Nora Mejri",
           @"Yara Mathilda Melki",
           @"Helmi Mourad",
           @"Jana Mukaddam",
           @"Fadi Nashawati",
           @"Raya Nasser",
           @"Hana Noureddin",
           @"Mona Noureddin",
           @"Tamara Oueidat",
           @"Celine Rafii",
           @"Yasmina Rai",
           @"Yara Rizk",
           @"Salma Saadeddine",
           @"Bashar Safieddine",
           @"Leila Safieddine",
           @"Karen Salam",
           @"Jana Sawaya",
           @"Rachel Sayed El",
           @"Omar Shair",
           @"Dalia Shaker",
           @"Michelle Shukri",
           @"Aya Sleiman",
           @"Ghadi Sleiman",
           @"Lynn Sleiman",
           @"Luca M. Smimmo",
           @"Imad Solh El",
           @"Siham Soueid",
           @"Husein Soufan",
           @"Ariana Anastassia Sursock Cochrane",
           @"Adnan Tabbara",
           @"Shady Tawil",
           @"Seif Tayeb",
           @"Mariam Tzannatos",
           @"Layan Yamani",
           @"Yasmine Yamout",
           @"Nadim Yashruti",
           @"Issam Zantout",
           @"Taj Zantout",
           @"leila Zein Al",
           @"Abdel Halim Zein El",
           @"Adam Zorkot",
           @"Jad Abbas",
           @"Mohammed Abdul Rassoul",
           @"Leah Abdul Reda",
           @"Hannah Abi Saab",
           @"Nadeem Abs",
           @"Lara Abu Musa",
           @"Ali Achour",
           @"Ali Alameh",
           @"Karim Alami",
           @"Moh. Salim Ammouni",
           @"Maha Andari Al",
           @"Rim Annan El",
           @"Zayane Arafat",
           @"Hind Arayssi",
           @"Raed Assaad",
           @"Tara Assaad El",
           @"Kareem Assaad El",
           @"Wadad Assaf",
           @"Reem Assi",
           @"Jad Awar Al",
           @"Omar Ayoubi",
           @"Ghada Bakri",
           @"Layan Barhoumi",
           @"Omar Baydoun",
           @"Karim Baydoun",
           @"Mira Baydoun",
           @"Omar Bazerbachi",
           @"Ibrahim Bechara",
           @"Syma Bechara",
           @"Alia Bissat",
           @"Celine Bitar",
           @"Rani Bizri",
           @"Tayma Brasioli",
           @"GeorgePaul Cavalcanti",
           @"Nadim Chaarani",
           @"Aya Chahine",
           @"Moh. Ali Choucair",
           @"Talal Daher",
           @"Tarek Damerji",
           @"Lynn Dana El",
           @"Talal Dandachli El",
           @"Asma Dandan",
           @"Huda Mia Dandan",
           @"Malek Debs",
           @"Elie Dib",
           @"Reina Doumani",
           @"Lynn Ezzeddine",
           @"Leya Fadel El",
           @"Romy Faisal",
           @"Joseph Faisal",
           @"Samer Farhat",
           @"Ayad Farhat",
           @"Moufid Farra",
           @"Malek Fleyfel",
           @"Rashed Ghanem",
           @"Tarek Habre",
           @"Rasha Haddad",
           @"Rawan Hage Hassan",
           @"Lynn Hajj",
           @"Alan Mounir Hakim",
           @"Amin Halawi",
           @"Rita Halwani",
           @"Ramzi Hamade",
           @"Karim Hamed",
           @"Ribal Hamza",
           @"Adam Hariri El",
           @"Maya Hneidi",
           @"Ahmad Hobeichi",
           @"Mira Hoss El",
           @"Mohammad Ibrahim",
           @"Sarah Ibrahim Bacha",
           @"Jana Idriss",
           @"Farah Idriss",
           @"Luay Idriss",
           @"Jad Ismail",
           @"Jad Issa",
           @"Jana Itani",
           @"Cyma Itani",
           @"Karim Itani",
           @"Dima Itani",
           @"Imad Jaber",
           @"Ali Jammal",
           @"Atef Jubayli",
           @"Tala Kadi",
           @"Yasmina Kaissi",
           @"Mortada Kamareddine",
           @"Rina Kammoun",
           @"Omar Kanafani",
           @"Assem Kanso",
           @"Ramy Karam",
           @"Farah Katrib",
           @"Mohammad Khalil",
           @"Radah Khateeb Al",
           @"Hassan Khatib El",
           @"Zouheir Khayat El",
           @"Jana Khodr",
           @"AlHassan Khoshnan",
           @"Haya Koussa El",
           @"Kinda Maad",
           @"Serina Majzoub",
           @"Sarah Majzoub",
           @"Zayn Makdessi",
           @"Pauline Makdisi",
           @"Sara Makkouk",
           @"Yasmina Malak",
           @"Omar Mardini",
           @"Suheil Melhem Haidar",
           @"Malek Mneimne",
           @"Dana Mneimneh",
           @"Ahmad Mneimneh",
           @"Grace Ffion Moucharafieh",
           @"Mira Moussallati",
           @"Reeda Mroue",
           @"Zina Murad",
           @"Judy Naamani",
           @"Rafic Nahas",
           @"Yasmeen Nahas",
           @"Maya Najjar",
           @"Karim Nakfour",
           @"Nicole Nasrallah",
           @"Nabil Nasser",
           @"Mia Natour El",
           @"Sirine Nehme",
           @"Fares Nsouli",
           @"Wael Osman",
           @"Lea Oueidat",
           @"Nadim Oueidat",
           @"Ali Rammal",
           @"Majd Rammal",
           @"Ramzi Rawdah El Balah",
           @"Lili Rayes El",
           @"Omar Rifai",
           @"Oliver Emile Rizk",
           @"Iya Hanan Saade",
           @"Lea Safa",
           @"Samir Safah",
           @"Raiya Sahyoun",
           @"Celine Samadi",
           @"Abdel Rahman Samadi",
           @"Antoine Samra",
           @"Tamar Sarkissian",
           @"Kristel Sayegh",
           @"Waleed Serbey",
           @"Samer Shammaa",
           @"Mustapha Shatila",
           @"Tamara Siblani",
           @"Ali Siblani El",
           @"Philip Skaf",
           @"Zeid Solh El",
           @"Sarah Tabbara",
           @"Amma Taddei",
           @"Houssein Taher",
           @"Tamer Tawil",
           @"Mohamad Tawil Al",
           @"Omar Tayara",
           @"Zeyd Tayeb",
           @"Isaac Tchaprazian",
           @"Layan Wahidi",
           @"Suha Wazni",
           @"Ali Yamout",
           @"Kamal Yassine",
           @"Ibrahim Yassine",
           @"Noura Zaim Al",
           @"Wafic Zantout",
           @"Aya Zeenni",
           @"Tarek Zein El Abidine",
           @"Jennifer Berrou",
           @"Dani Fakih",
           @"Judy Idriss",
           @"Marie-Nour Karam",
           @"Mohamad Keaik",
           @"Naya Sakr",
           @"Ghalia Tawil",
           @"Lynn Abboud",
           @"Rindala Ahdab (El)",
           @"Jasmine Arab (El)",
           @"Lynn Chmaitelly",
           @"Carol Ezzeddine",
           @"Ahmad Farhat",
           @"Mohamad Haidar",
           @"Ali Hajaij",
           @"Raja Haroun",
           @"Sally Hunini",
           @"Mira Jaber",
           @"Nour Mougharbel",
           @"Oumaya Mougharbel",
           @"Nader Nasr",
           @"Ali Nawlo",
           @"Aya Nouh",
           @"Yehya Noureddine",
           @"Karim Sabbagh (Al)",
           @"Bassil Shami",
           @"Sara Tannir (El)",
           @"Karim Wansa",
           @"Rachid Wansa",
           @"Omar Ramadan",
           @"Ahmad Ramadan",
           @"Mohammad Koeik",
           @"Hania Abbas",
           @"Fadi Noueihed",
           @"Ahmad Bachacha",
           @"Karim Beydoun",
           @"Jad Assi",
           @"Layane Mekawi",
           @"Amal Zaim",
           @"Amal Charara",
           @"Carine Arayssi Saad",
           @"Shafia Farran",
           @"Carol Saliba",
           @"Christian Tawtel",
           @"Doumiana Ayyoub",
           @"Darine Fenianos Dergham",
           @"Dolly Awad",
           @"Dona Nassif",
           @"Dana Tayan",
           @"Elie Hayek",
           @"Fatima Baalbaki",
           @"Fida Malak",
           @"Fida Nashef",
           @"Fatima Turbah",
           @"Ghada Itani",
           @"Hania Abu Rihan",
           @"Hind Farra",
           @"Hanan Sabra",
           @"Hoda Tarraf",
           @"Imane Ramadan",
           @"Juliette Bikhazi",
           @"Kawsar Farchoukh",
           @"Khadija Hamzah",
           @"Lama Shihab",
           @"Nahla Jamaleddine",
           @"Rola Sleiman",
           @"Samar Kandil",
           @"Nabila Hemadeh",
           @"Natalie JouJou",
           @"Rim Zaytoun",
           @"Mona Chidiac",
           @"Mohamad Khalil Al",
           @"Mirella Saad",
           @"Mary Sacre",
           @"Mireille Tavitian",
           @"Mounira Yamout",
           @"Noel Bou Abboud",
           @"Osman Osman",
           @"Rasha Hammoud",
           @"Ranwa Jeha",
           @"Rabia Kaddah",
           @"Rana Kaoury",
           @"Rima Khishen",
           @"Randa Sabbah",
           @"Sawsan Abdel Malak",
           @"Samiha Ghusayni",
           @"Soha Hamdan",
           @"Serine Jaafar",
           @"Sawsan Kibbi",
           @"Samar Noueihed",
           @"Sarah Hajj Sleiman",
           @"Samar Zein El Abidine",
           @"Zeina Komboz",
           @"Zeina Rawas El",
           @"Catherine Kronke",
           @"Zeinab Khatoun",
           @"Randa ElKhatib",
           @"Myriam Gharby",
           @"Carla Antar",
           @"Ryan Enser",
           @"Zeinab Haidar",
           @"Maya Elie Karam",
           @"Ryan Lee",
           @"Chaza Kalach",
           @"Adnan Hajj Ali Barada",
           @"Ahmad Dana",
           @"Arnaud Le DÃ»",
           @"Dagher Mehanna",
           @"Elie Mokbel",
           @"Eddy Tohme",
           @"Farah Mouhanna",
           @"Fouad Succar",
           @"Fatima Taha",
           @"Hind Abou Rislan",
           @"Hatem Chalak",
           @"Hamdi Houalla",
           @"Hana Majzoub",
           @"Hussein Said",
           @"Iskandar Abou Kasm",
           @"Iman Jawhari",
           @"Josephine Bou Dagher",
           @"Josette Eid",
           @"Jeanette Frangieh",
           @"Josette Gabayen",
           @"Jeanne Khoury El",
           @"Jocelyne Kobeissi",
           @"Khalil Khoury",
           @"Myriam Abou Atmeh",
           @"Maysoun Ali Al",
           @"Marina Baltikian",
           @"Sevag Atamian",
           @"Maha Shukayr",
           @"Majida Chatila",
           @"Malda Dirani",
           @"Marielle Hajj Sleiman",
           @"Marina Sleiman",
           @"Nabih Fawaz",
           @"Najah Hawwa",
           @"Nabih Lahoud",
           @"Nazha Salameh Fhaily",
           @"Nisrine Chahrour",
           @"Patricia Hamra",
           @"Rodolphe Abboud",
           @"Rawane Naja Ajam",
           @"Rola Ayache",
           @"Rasha Daouk",
           @"Rima Khatib",
           @"Rita Maghames Souaid",
           @"Rita Esta El",
           @"Reda Saleh",
           @"Randa Azkoul",
           @"Samia Boulad",
           @"Salma Kojok",
           @"Samir Rishmani",
           @"Souheil Zarifeh",
           @"Tatiana Bondarovich Samaha",
           @"Tarek Kanso",
           @"Tarek Moussally",
           @"Victoria Abboud",
           @"Veronique Karam",
           @"Wissam Kabbani",
           @"Edward Khairallah",
           @"Farid Karam",
           @"Hussam Kasti",
           @"Silvana Bartlett",
           @"Afaf Assaad",
           @"Najla Nakhle",
           @"Eduardo Carrasco",
           @"Roland Homsy",
           @"Pedro Maalouf",
           @"Anya Michelle Arndt",
           @"Carmen Ibrahim",
           @"Najia kambris",
           @"Ghida Molaeb",
           @"Abdullah Namroud (El)",
           @"Hanane whaibe",
           @"Lara Assi Al",
           @"Aref Abou Hamzeh",
           @"Carl Farhat",
           @"Sandra Berjawi",
           @"Samir Andari",
           @"Michel Abdel Jalil",
           @"Amin Dana",
           @"Jeremy Ghorayeb Chabtini",
           @"Luka Nader",
           @"Sara Ayoub",
           @"Carli Abraham",
           @"Nour Choucair",
           @"Karen Abdallah",
           @"Malak AbdulRassoul",
           @"Tammar Adday",
           @"Jad Alame",
           @"Hadi Bizri",
           @"Rashad BouDiab",
           @"Maya Gavin",
           @"Reem HageHassan",
           @"Riam Hakim",
           @"Yasmeen Hamadeh",
           @"Rami Jarmakani",
           @"Lanna Kuba",
           @"Lucia Najjar",
           @"Bethany Nasrallah",
           @"Jad Rifai",
           @"Tala Soweid",
           @"Joanna Zbib",
           @"Lina Alami",
           @"Amer Bleik",
           @"Tarek Chahine",
           @"Sarah Chamli",
           @"Samir Ghandour",
           @"Basheer Hijal",
           @"Toufic Houri",
           @"Zeinab Ibrahim",
           @"Karim Itani",
           @"Wajih Jaroudi",
           @"Tarek KassemMoussa",
           @"Ramzi Kawas",
           @"Ghalia Khalili",
           @"Wael Kharoubi",
           @"Hisham Osman",
           @"Yasmine Ouri",
           @"Yasmina Sayyed",
           @"Reem Siblini",
           @"Yasmina Zamel",
           @"Sarah Annan",
           @"Habiba Arab",
           @"Ramzi Chaaban",
           @"Khalil Chahine",
           @"Hind Fayad",
           @"MichaKhalid Ghutmi",
           @"HusseinSonny Hamdan",
           @"Maria Harb",
           @"Omar Itani",
           @"Mohammad Kattan",
           @"Yara Khalil",
           @"Eva Malik",
           @"Bahia Mkhallati",
           @"Nour Najjar",
           @"Maya Nasser",
           @"Karim Saridar",
           @"Samer Sharif",
           @"Arkan Siblani",
           @"Ramzi Tabsh",
           @"Ayad Zamel",
           @"Rayan Zein",
           @"Elissa AbdelKhalek",
           @"Zeina AbouChahine",
           @"Hassan Antar",
           @"Manuella Asmar",
           @"Ihab Beydoun",
           @"Carine Bitar",
           @"Dima Chahine",
           @"Dima Daouk",
           @"AbdulLatif Hassan",
           @"Sami IbrahimBasha",
           @"Celina Kayssi",
           @"Hicham Khaled",
           @"Christina Khawaja",
           @"Karim Koussa",
           @"Rami Mortada",
           @"Hussein Nasreddine",
           @"Jad Salha",
           @"Hikmat Soubra",
           @"Karim Takieddine",
           @"Talal Akkaoui",
           @"Mazen Assaf",
           @"Nour Assi",
           @"Talal Azhari",
           @"TamaraSiham Cheikha",
           @"Raymond Edde",
           @"Omar Fadel",
           @"Rashad Fakhouri",
           @"Karim Hakim",
           @"Nadim Hassan",
           @"Lynn Houssami",
           @"Nour Jizi",
           @"RayLynn Kaedbey",
           @"Mia Mansour",
           @"Mahmoud Masri",
           @"Haya Mroueh",
           @"Ryan Raphael",
           @"Ali Yaacoub",
           @"Asmaa Zantout",
           @"Paul Adaimi",
           @"Nadine Baker",
           @"Faysal Berjawi",
           @"Bassem Chaaban",
           @"Rabab Charafeddine",
           @"Omar Husami",
           @"Sara Inkidar",
           @"Tamara Kadi",
           @"Elissa Khalil",
           @"Sarah Kheireddine",
           @"Basma Kraytem",
           @"Lea Ladki",
           @"Ali Majed",
           @"Jade Maktabi",
           @"Marya Malki",
           @"Rami Masri",
           @"Jawdat Mirza",
           @"Nadim Saridar",
           @"Moustafa Tabbarah",
           @"Karim Talih",
           @"Ghida Alameh",
           @"Nadim Arasoghli",
           @"MohHassan Assaf",
           @"Aman Chaarani",
           @"Karim Dandan",
           @"Sarah Ftouni",
           @"Reem Haddad",
           @"Sary Hafez",
           @"MohammadOmar Hallab",
           @"Mohammad Husseini",
           @"Aya Idriss",
           @"Karim Kabbani",
           @"Riwa Kanj",
           @"Ramzi Kattouf",
           @"Wassim Maktabi",
           @"Dounia Masri",
           @"MohTarek Rifai",
           @"Tatiana Saade",
           @"Karam Safi",
           @"Lea Sakr",
           @"Lynn Tayara",
           @"Amer Ammache",
           @"Tony Asfour",
           @"Ryan Bajjani",
           @"Nathalie Chahrour",
           @"Lina Charafeddine",
           @"Mira Dagher",
           @"Tala Dalal",
           @"Jamil Darwish",
           @"Ali Faraj",
           @"Samuel Ghattas",
           @"Karim Jalloul",
           @"Firas Jarmakani",
           @"Ghia Koussa",
           @"Michael Majdalani",
           @"Zainab SadekTaher",
           @"Zeid Shair",
           @"Aya Slim",
           @"Catrina Ziade",
           @"Amine Abs",
           @"Racha Akel",
           @"Hiba Choucair",
           @"Marian Dabbagh",
           @"Ali Fakih",
           @"Mohamad Fleyfel",
           @"Sara Ghandour",
           @"Daniella Haidar",
           @"Reina Hasbini",
           @"Nadia Khalil",
           @"Monah Khatib",
           @"Karim Mahdi",
           @"Amal Moumneh",
           @"Layan Murad",
           @"Hussein Nasser",
           @"Khalid Nouh",
           @"Sami Osseiran",
           @"Aya Safieddine",
           @"Amer Shamaa",
           @"Ghida Anouti",
           @"Lama Dakik",
           @"Hadi Ezzeddine",
           @"Hala Haddad",
           @"Ghida Hamiyeh",
           @"Ramzi Harake",
           @"Tala Hout",
           @"Bassel Hussein",
           @"Fatima Ibrahim",
           @"Huda Kandil",
           @"Hadi Kassar",
           @"Mohamad Khachfe",
           @"Mahmood Khalil",
           @"Ahmad Khatib",
           @"Alaa Mounzer",
           @"Alia Najjar",
           @"MohammadAli Saadeddine",
           @"Aya Safieddine",
           @"Nour Sheikh",
           @"Dahlia Yamout",
           @"Dareen AboulMouna",
           @"Sarah Baba",
           @"Lama Barhoumi",
           @"Fouad Bitar",
           @"Nadim Captan",
           @"Caroline Dbouk",
           @"Noura Derian",
           @"MohamadAlaa Fleifel",
           @"Reem Ghaziri",
           @"Ramsey Hout",
           @"Ghida Koteiche",
           @"Samer Mortada",
           @"Hamed Mounla",
           @"Yara Mourad",
           @"Christopher Raffoul",
           @"Bassem Saghir",
           @"Nicholas Salloum",
           @"Marya Wahidi",
           @"AliUsama Zreik",
           @"Sara Abdo",
           @"Houssein Bdeir",
           @"Ezzat Chebaro",
           @"Nizar Choucair",
           @"LeaLynn Dandan",
           @"Mostafa Fakhani",
           @"Aya Fathallah",
           @"Tarek Ghandour",
           @"Husein HageHassan",
           @"Adam Jammal",
           @"Keenan Jarmakani",
           @"Tarek KaissiTamuri",
           @"Jad Kanaan",
           @"Reem Katrib",
           @"Elmira Maktabi",
           @"Salim Musleh",
           @"Patile Nahabedian",
           @"Sara Najjar",
           @"Dina Richani",
           @"Maya Zebian",
           @"Malek Akkaoui",
           @"Faysal Assaad",
           @"Mohamad Tarif Ayoubi",
           @"Luna Azar",
           @"Sabrina Bouri",
           @"AyaLynn Dandan",
           @"Mia Debbas",
           @"Xenon Fallaha",
           @"Ramy Fawaz",
           @"Kevin Gedeon",
           @"Yasmina Ghadban",
           @"Michel Harmouche",
           @"RakanKamal HusniBey",
           @"HasanDaniel Kaedbey",
           @"Karim Kassem",
           @"Wassef Kassem",
           @"SayleRichard Makdessi",
           @"Antoine Melki",
           @"Tarek Mroueh",
           @"Amine Nakadi",
           @"Jeremy Tavitian",
           @"Karen Zeenny",
           @"Sajia Assaad",
           @"Zeina Bazerbachi",
           @"Sami BouKhaled",
           @"Ali Chamout",
           @"Dalia Dandan",
           @"Youssof Daouk",
           @"Rani Ezzedine",
           @"Rayya Fahed",
           @"Stefano Fallaha",
           @"FaroukVance Grissom",
           @"Karim Habre",
           @"Emile Kanazi",
           @"Dina Mansour",
           @"Nouhad Maoula",
           @"Nader Nammour",
           @"Yasmine Osseiran",
           @"Natalie Saadeh",
           @"Bakri Sakr",
           @"Grace Shaib",
           @"Sabine Sinno",
           @"Sarah Wehbe",
           @"Karim Yaghi",
           @"Joseph Zaidan",
           @"Karim ZeinElAbidine",
           @"Ghadi AbuMusa",
           @"Ziad Assaf",
           @"Yara Bekdache",
           @"Malek Daouk",
           @"Youssef Hadi",
           @"Yasmine Haydar",
           @"MohKarim Jaber",
           @"Rawi Kammoun",
           @"Karim Majed",
           @"Lea Maktabi",
           @"Aya Merhebi",
           @"Yasmine Mourad",
           @"Yasmina Moussally",
           @"Karma Mroueh",
           @"Karim Nashawati",
           @"Lana Nsouli",
           @"Sarah Osman",
           @"Nour Ramadan",
           @"Yasmina Siblani",
           @"Assem Sweidan",
           @"Riad Tabbara",
           @"Mostafa Takkoush",
           @"May Abiad",
           @"Alia Bakir",
           @"Jad Beydoun",
           @"Karim Bizri",
           @"Samer Captan",
           @"Rewa Haidar",
           @"Karim Hajj",
           @"Ali Ibrahim",
           @"Rola Itani",
           @"Mutaz Kassas",
           @"Yasmeen Nasser",
           @"MohAli Rachid",
           @"Ahmad Rawas",
           @"AbdulHafiz Tannir",
           @"Lara Tawil",
           @"Musallam Zayed",
           @"AbdelRahman Ammouni",
           @"Tala Darwish",
           @"Ali Hashim",
           @"Noura Hassouna",
           @"Karen Ibrahim",
           @"RayanTarek Karout",
           @"Marwan Kassar",
           @"Ahmed KassemMoussa",
           @"Adi Khatib",
           @"DanaMaria Kibbi",
           @"Roya Mahfouz",
           @"Wassim Rahal",
           @"Patrick Rizk",
           @"Mohamad Sahely",
           @"Toufic Saridar",
           @"Zein AliAhmad",
           @"Sawsan Dargham",
           @"Rasha Eid",
           @"Karim Harakeh",
           @"Nour Hasbini",
           @"Dana Houalla",
           @"Danny Ibrahim",
           @"Marwan Jalaleddine",
           @"Ramzi Kibbi",
           @"MohBahij Moumneh",
           @"Ryan Osgueritchian",
           @"Lara Oueidat",
           @"Zoe Saade",
           @"Omar Saadeddine",
           @"Aya SheikhIsmail",
           @"Julia AbiSaab",
           @"Patrick Akoury",
           @"Adnan Ammache",
           @"MohKarim Atwi",
           @"Celine Charlier",
           @"Claudia Chidiac",
           @"Dana Darwish",
           @"DanielGeorges Faddoul",
           @"Zainab Faraj",
           @"Kamal Ghandour",
           @"Ziad Haffar",
           @"Dalia Hneidi",
           @"RamaRuwiada Hojeij",
           @"Samar Itani",
           @"Peter Kay",
           @"Michael Moualem",
           @"ChristianPaul Nemer",
           @"Karim Salam",
           @"Dana Wazneh",
           @"Omar ZeinElAbidine",
           @"Ramsey Akl",
           @"Marc Akoury",
           @"Maia Asfour",
           @"Nour Baydoun",
           @"Mariam Boustani",
           @"ChristinaMaria Cavalcanti",
           @"Carl Ghattas",
           @"Sultan Itani",
           @"Juliette Jabra",
           @"Noura Jawhar",
           @"Steven Karam",
           @"Hania Khatib",
           @"Ali Kodeih",
           @"Ramsey Marrouche",
           @"Hannah Millet",
           @"Ahmad Rifai",
           @"Raneem Salha",
           @"Feras Wahab",
           @"Ara Yerevanian",
           @"Maha Ammache",
           @"Nour Awar",
           @"Nour Chanouha",
           @"Lara Chehabeddine",
           @"MarcElie Comair",
           @"Paul Edde",
           @"Jirji Haddad",
           @"Lynn Hanna",
           @"Omar Idriss",
           @"Maxime Isaac",
           @"Sana Jamali",
           @"Georges Kanaan",
           @"Fouad Khalifa",
           @"Shireen Khatib",
           @"AbdelSalam Lahham",
           @"Salah Mneimne",
           @"Wajih Naamani",
           @"Ghida Nadar",
           @"Souraya Nasser",
           @"Adam Ouayda",
           @"Layane Sakr",
           @"Firas Abbas",
           @"Maher AbdelSamad",
           @"Sama Achour",
           @"Mohammad Araoui",
           @"Fares Attar",
           @"Khalil Bechara",
           @"Mustafa Berry",
           @"Karim Dana",
           @"Sarah Fil",
           @"Hassan Ghoul",
           @"Karim Hafez",
           @"Nour Husami",
           @"Yasmine Itani",
           @"Reine Jamali",
           @"Mayssa Jaroudi",
           @"Haya Kady",
           @"Sara Kalo",
           @"Judy Malki",
           @"Alex Mardelli",
           @"Karim Masri",
           @"Mohammad Mneimneh",
           @"Mounzer Tabbarah",
           @"Dalia Barazi",
           @"Noura Baroudy",
           @"Ralph Bassim",
           @"Malek Bsat",
           @"Moussa Charafeddine",
           @"Tala Chehayeb",
           @"Sirine Darwiche",
           @"Nassif Eid",
           @"EmileElieAntoine Geagea",
           @"Ahmad Hajj",
           @"Jad Harb",
           @"Tala Hibri",
           @"Dani Inkidar",
           @"Raha Itani",
           @"Nour Jamil",
           @"Lynn Jaroudi",
           @"Kazem Khalil",
           @"Omar Makarem",
           @"Karim Nazha",
           @"Nagham Osman",
           @"Yasmina Taher",
           @"Rawad Yehia",
           @"Wadih Zgheib",
           @"Charles Abraham",
           @"Walid Bamehriz",
           @"Peter Beaini",
           @"Tarek Bounassif",
           @"Elias Chabab",
           @"Antoine Chbeir El",
           @"Daniel Daher",
           @"Cedric Gulumian",
           @"Tara Hakim",
           @"Ziad Hawa",
           @"Farid Milad",
           @"Sabine Nahabedian",
           @"Yazmin-Rose Rizk",
           @"Cyril Saroufim",
           @"Elena Tohme",
           @"Fawzi Balaa",
           @"Carl-Eric Daniel",
           @"Nirsine Doumit",
           @"Nadia-Lara Samaha",
           @"Ayad-Patrick Saoud",
           @"George Tohme",
           @"Nicolas Abouhaidar",
           @"Mark Eke",
           @"Elias Haddad",
           @"Nadim Hawa",
           @"George Jarrouj",
           @"Christina Katbe",
           @"Taleed Maamari",
           @"Dimitri Melki",
           @"Antoine Saber",
           @"Harry Simitian",
           @"Wissam Abdelnour",
           @"Iyad-Sam Abouchahla",
           @"Sherif Aoun",
           @"Youssef Bassil",
           @"Raya Chemayaa",
           @"Michel Dibo",
           @"Tamara Geadah",
           @"Karl-Mark Hadife",
           @"Charbel Jabra",
           @"Patrick-Joe Kfoury",
           @"Yahya Khalilel",
           @"Omar Nasser",
           @"Nancy Nouhra",
           @"Nour Saliba",
           @"Jana Sawaya",
           @"Fares Tabet",
           @"Reef-Carla Torbey",
           @"Ihab Younes",
           @"Sasha Abela",
           @"Sirene Abiad",
           @"Priscilla Aboukaram",
           @"Sophie Akoury",
           @"Jack Azadian",
           @"Ghaysa Azar",
           @"Jad Chaanine",
           @"Salome Charvet",
           @"Mariam Dahdahel",
           @"Celine Haddad",
           @"Jimmy Name",
           @"Nadim Nassar",
           @"Chafic Nasser",
           @"Romy Nehme",
           @"Joseph Saad",
           @"Maria Tohme",
           @"Malak Yacout",
           @"Clara Zarka",
           @"Alessandro Zraick",
           @"Issam Ariss",
           @"Karim Asmar",
           @"Mark Azadian",
           @"William Azar",
           @"Joey-Bahige Chammas",
           @"Laura Debbane",
           @"Charles Eid",
           @"Christelle Feghaliel",
           @"Laura Ghattas",
           @"Erik Hadife",
           @"Joceline Hageel",
           @"Isabella Khouryel",
           @"Tala Mardelli",
           @"Adel Rizk",
           @"Pierre Abillama",
           @"Lina Aboujaoude",
           @"Samir Boutros",
           @"Carlie Chahine",
           @"Alain Daccache",
           @"Michel Farah",
           @"Marc Khair",
           @"Kamal Kharratel",
           @"Yara-Michele Labban",
           @"Kim Naja",
           @"Leah-Rosemary Rassie",
           @"Maria-Jane Rebeiz",
           @"Jean-Paul Rizk",
           @"Laetitia Sebaaly",
           @"Dana-Maria Tohme",
           @"Mourad Younes",
           @"Khataline Zogheib",
           @"Joseph Abboud",
           @"Miriam Abitarabay",
           @"Lea Atallah",
           @"Ghassan-Andrew Attieh",
           @"Tanya Azar",
           @"Rana Boustany",
           @"Andrea Chamaa",
           @"Crystelle Daaboul",
           @"Michelle Dagher",
           @"Karim-Sergei Dahrouge",
           @"Beatrice Doumet",
           @"Mario Doumet",
           @"Tala Farah",
           @"Karl Hawael",
           @"Mayelle Jabbour",
           @"Jad-Elie Kodeih",
           @"Pierre Matta",
           @"Wael Merhi",
           @"Lea Zeidan",
           @"Adriana Zraick",
           @"Aya-Maria Abouchahla",
           @"Charly Chedrawi-Laba",
           @"Catherine-Maria Choumali",
           @"Mounir Dahdahel",
           @"Anthony-Albert Flouty",
           @"Malek Geadah",
           @"Georgy Hadife",
           @"Cynthia Hitti",
           @"Sam Kebbe",
           @"Mario Nohra",
           @"Marla Noumair",
           @"Estelle Raphael",
           @"Karim Rizcallah",
           @"Talia Rizk",
           @"Sarine-Laura Tutunjian",
           @"Nour Eid",
           @"Alessandro Khoury",
           @"Dana Ataya",
           @"Andrew Bismar",
           @"Mustapha Dandachli El",
           @"Georges Gedeon",
           @"Maher Jurdi",
           @"Albert Minassian",
           @"Sara Sabbah",
           @"Jad Sleiman",
           @"Jana Wafa",
           @"Karim Arabi",
           @"Nadia Ramadan",
           @"Marwan Sakr",
           @"Hani Abou Farhat",
           @"Bassel Fares",
           @"Rasha Haidar",
           @"Amer Hatoum",
           @"Ghazi Loulou Al",
           @"Saad Majzoub Al Sabbagh Al",
           @"Nour Moufarrej",
           @"Diane Nawbar",
           @"Issa Noureddine",
           @"Carelle Rhayem",
           @"Ahmad Saadi El",
           @"Maya Saleh",
           @"Jad Shahine",
           @"Abdul Rahim Tabbara",
           @"Ali Tarhini",
           @"Karim Adada",
           @"Yara Abboud",
           @"Ramzi Abou Chahine",
           @"Malek-Pierre Arif",
           @"Tarek Awad",
           @"Michel Azar",
           @"Selina Baaklini",
           @"Ahmad Bdeir",
           @"Noura Bistami (Al)",
           @"Dana Diab",
           @"Robert Georges Raad Farajalla",
           @"Jad Haidar",
           @"Marina Hasan",
           @"Lea Helou",
           @"Israa Hoss (El)",
           @"Julia Gabrielle Jerab",
           @"Victoria Kabalan",
           @"Ibrahim Kandil",
           @"Mahmoud Koleilat",
           @"Fadi Makdisi",
           @"Ahmad Makki",
           @"Nour Malaeb",
           @"Ramzi Maluf",
           @"Sana Mansour",
           @"jasmin Nasr",
           @"Yasmina Nuwayhed",
           @"Firas Rafeh",
           @"Sara Rafeh",
           @"Jacques Raphael",
           @"Samira Takkoush",
           @"Leila Berry",
           @"Ismat Annan",
           @"Ahmad Arakji",
           @"Nadine Ayoub",
           @"Celine Bitar",
           @"Tala Chehaitly",
           @"Ibrahim Ghaddar",
           @"Abdul Aziz Hajjaj (Al)",
           @"Ziad Harb",
           @"Farouk Houri",
           @"Dima Malaeb",
           @"Rewa Mneimneh",
           @"Ghadi Mohammad Fouad",
           @"Wassim Radwan",
           @"Nathalie Sabbagh (El)",
           @"Nour - Sabah Shami",
           @"Ali Slim",
           @"Yara Tayeh",
           @"Kareem Tinawi",
           @"Yasmine Wehbi",
           @"Tala Zeineddine",
           @"Fouad Amine (El)",
           @"Nour Bakhos",
           @"Toufic Braidi",
           @"Firas Dahi",
           @"Rawad Fares",
           @"Nora Fatayerji",
           @"Valerie Festekdjian",
           @"Bassem Hammoudi",
           @"Rita-Maria Kenaan-Rahbani",
           @"Samar Khatib (El)",
           @"Jana Mahmassani",
           @"Joseph Mourad",
           @"Ralph Sabbagh",
           @"Ayla Ghrawi",
           @"Zahra Abdallah",
           @"Ahmad Bitar",
           @"Robina Dandachli (El)",
           @"Hassan Mahfouz",
           @"Hussein Mahfouz",
           @"Lauren Christy Sfeir",
           @"Amer Sleiman",
           @"Mariam Zaidan",
           @"Ahmad Zakka",
           @"Gregory Torbey",
           @"Sulayman Darwish",
           @"Martina Monteduro",
           @"Ghida Dalloul",
           @"Sarah Jarroush",
           @"Abdul Rahman Mahayni",
           @"Alia Beydoun"
           ];
  
}

- (NSArray*)studentUserIDs {
  return @[
           @"73",
           @"74",
           @"179",
           @"356",
           @"365",
           @"366",
           @"767",
           @"805",
           @"2338",
           @"2340",
           @"2342",
           @"2345",
           @"2346",
           @"2347",
           @"2350",
           @"2351",
           @"2353",
           @"2354",
           @"2356",
           @"2357",
           @"2358",
           @"2359",
           @"2538",
           @"2539",
           @"2540",
           @"2542",
           @"2543",
           @"2544",
           @"2545",
           @"2546",
           @"2547",
           @"2548",
           @"2549",
           @"2550",
           @"2551",
           @"2552",
           @"2553",
           @"2554",
           @"2555",
           @"2557",
           @"2558",
           @"2559",
           @"2560",
           @"2562",
           @"2563",
           @"2564",
           @"2565",
           @"2566",
           @"2567",
           @"2568",
           @"2569",
           @"2570",
           @"2571",
           @"2573",
           @"2575",
           @"2576",
           @"2579",
           @"2581",
           @"2582",
           @"2584",
           @"2585",
           @"2586",
           @"8643",
           @"8644",
           @"8645",
           @"8646",
           @"8647",
           @"8648",
           @"8650",
           @"8651",
           @"8652",
           @"8653",
           @"8654",
           @"8655",
           @"8656",
           @"8657",
           @"8658",
           @"8659",
           @"8661",
           @"8663",
           @"8664",
           @"8665",
           @"8666",
           @"8667",
           @"8668",
           @"8669",
           @"8670",
           @"8671",
           @"8672",
           @"8673",
           @"8674",
           @"8675",
           @"8676",
           @"8678",
           @"8679",
           @"8681",
           @"8682",
           @"8683",
           @"8684",
           @"8685",
           @"8686",
           @"8687",
           @"8688",
           @"8689",
           @"8690",
           @"8691",
           @"8692",
           @"8693",
           @"8694",
           @"8695",
           @"8696",
           @"8697",
           @"8699",
           @"8700",
           @"8701",
           @"8702",
           @"8703",
           @"8704",
           @"8706",
           @"8707",
           @"8708",
           @"8709",
           @"8710",
           @"8711",
           @"8712",
           @"8713",
           @"8714",
           @"8715",
           @"8716",
           @"8717",
           @"8718",
           @"8720",
           @"8721",
           @"8724",
           @"8725",
           @"8727",
           @"8728",
           @"8729",
           @"8731",
           @"8732",
           @"8735",
           @"8736",
           @"8738",
           @"8739",
           @"8740",
           @"8741",
           @"8743",
           @"8745",
           @"8746",
           @"8747",
           @"8748",
           @"8751",
           @"8752",
           @"8753",
           @"8754",
           @"8755",
           @"8756",
           @"8758",
           @"8760",
           @"8762",
           @"8763",
           @"8764",
           @"8766",
           @"8767",
           @"8768",
           @"8769",
           @"8770",
           @"8771",
           @"8772",
           @"8773",
           @"8774",
           @"8775",
           @"8776",
           @"8777",
           @"8779",
           @"8780",
           @"8781",
           @"8782",
           @"8783",
           @"8784",
           @"8785",
           @"8786",
           @"8787",
           @"8788",
           @"8789",
           @"8791",
           @"8792",
           @"8796",
           @"8798",
           @"8799",
           @"8800",
           @"8801",
           @"8803",
           @"8804",
           @"8805",
           @"8806",
           @"8807",
           @"8809",
           @"8811",
           @"8812",
           @"8814",
           @"8815",
           @"8816",
           @"8817",
           @"8819",
           @"8820",
           @"8821",
           @"8822",
           @"8824",
           @"8825",
           @"8831",
           @"8832",
           @"8837",
           @"8838",
           @"8839",
           @"8842",
           @"8843",
           @"8844",
           @"8845",
           @"8846",
           @"8849",
           @"8850",
           @"8851",
           @"8853",
           @"8855",
           @"8856",
           @"8857",
           @"8858",
           @"8859",
           @"8860",
           @"8861",
           @"8864",
           @"8865",
           @"8866",
           @"8867",
           @"8868",
           @"8869",
           @"8871",
           @"8872",
           @"8873",
           @"8874",
           @"8875",
           @"8877",
           @"8878",
           @"8879",
           @"8880",
           @"8881",
           @"8883",
           @"8884",
           @"8885",
           @"11859",
           @"39694",
           @"123",
           @"148",
           @"168",
           @"172",
           @"183",
           @"201",
           @"205",
           @"209",
           @"240",
           @"252",
           @"254",
           @"307",
           @"313",
           @"323",
           @"335",
           @"347",
           @"350",
           @"665",
           @"680",
           @"688",
           @"710",
           @"721",
           @"729",
           @"732",
           @"757",
           @"838",
           @"852",
           @"860",
           @"865",
           @"39984",
           @"39990",
           @"61926",
           @"61935",
           @"61939",
           @"61950",
           @"1610",
           @"1611",
           @"1612",
           @"1613",
           @"1614",
           @"1616",
           @"1618",
           @"1619",
           @"1620",
           @"1621",
           @"1622",
           @"1624",
           @"1625",
           @"1626",
           @"1627",
           @"1629",
           @"1630",
           @"1632",
           @"1634",
           @"1635",
           @"1636",
           @"1637",
           @"1639",
           @"1641",
           @"1642",
           @"1643",
           @"1644",
           @"1645",
           @"1646",
           @"1647",
           @"1649",
           @"1650",
           @"1651",
           @"1652",
           @"1653",
           @"1654",
           @"1656",
           @"1657",
           @"1658",
           @"1659",
           @"1661",
           @"1662",
           @"1663",
           @"1664",
           @"1665",
           @"1666",
           @"1667",
           @"1668",
           @"1669",
           @"1670",
           @"1671",
           @"1672",
           @"1673",
           @"1674",
           @"1676",
           @"1677",
           @"1678",
           @"1679",
           @"1681",
           @"1683",
           @"1684",
           @"1685",
           @"1686",
           @"1687",
           @"1688",
           @"1692",
           @"1693",
           @"1695",
           @"1696",
           @"1697",
           @"1698",
           @"1699",
           @"1712",
           @"2196",
           @"2206",
           @"2253",
           @"2258",
           @"2259",
           @"2260",
           @"2261",
           @"2262",
           @"2263",
           @"2264",
           @"2265",
           @"2267",
           @"2268",
           @"2269",
           @"2271",
           @"2272",
           @"2273",
           @"2274",
           @"2276",
           @"2277",
           @"2278",
           @"2279",
           @"2280",
           @"2281",
           @"2282",
           @"2283",
           @"2284",
           @"2285",
           @"2287",
           @"2288",
           @"2289",
           @"2290",
           @"2291",
           @"2293",
           @"2294",
           @"2295",
           @"2296",
           @"2297",
           @"2298",
           @"2299",
           @"2300",
           @"2301",
           @"2302",
           @"2303",
           @"2304",
           @"2306",
           @"2307",
           @"2308",
           @"2309",
           @"2311",
           @"2312",
           @"2314",
           @"2315",
           @"2316",
           @"2317",
           @"2318",
           @"2319",
           @"2320",
           @"2321",
           @"2322",
           @"2323",
           @"2324",
           @"2325",
           @"2326",
           @"2327",
           @"2328",
           @"2329",
           @"2330",
           @"2331",
           @"2333",
           @"2334",
           @"2335",
           @"2336",
           @"2337",
           @"2339",
           @"2343",
           @"2344",
           @"2352",
           @"2355",
           @"2580",
           @"2583",
           @"8662",
           @"8705",
           @"8722",
           @"8737",
           @"8742",
           @"8750",
           @"8790",
           @"8793",
           @"8795",
           @"8810",
           @"8818",
           @"8823",
           @"8826",
           @"8828",
           @"8829",
           @"8830",
           @"8835",
           @"8836",
           @"8852",
           @"8854",
           @"8863",
           @"8870",
           @"8876",
           @"8886",
           @"9806",
           @"9807",
           @"9808",
           @"9809",
           @"9810",
           @"9811",
           @"9812",
           @"9813",
           @"9814",
           @"9815",
           @"9816",
           @"9817",
           @"9818",
           @"9819",
           @"9820",
           @"9821",
           @"9823",
           @"9824",
           @"9825",
           @"9826",
           @"9827",
           @"9828",
           @"9829",
           @"9830",
           @"9831",
           @"9832",
           @"9833",
           @"9834",
           @"9835",
           @"9837",
           @"9838",
           @"9839",
           @"9840",
           @"9841",
           @"9842",
           @"9843",
           @"9844",
           @"9845",
           @"9846",
           @"9847",
           @"9848",
           @"9849",
           @"9850",
           @"9851",
           @"9852",
           @"9853",
           @"9854",
           @"9855",
           @"9856",
           @"9857",
           @"9858",
           @"9859",
           @"9860",
           @"9861",
           @"9862",
           @"9863",
           @"9864",
           @"9865",
           @"9866",
           @"9867",
           @"9868",
           @"9869",
           @"9870",
           @"9871",
           @"9872",
           @"9875",
           @"9876",
           @"9877",
           @"9878",
           @"9879",
           @"9880",
           @"9881",
           @"9882",
           @"9883",
           @"9884",
           @"9885",
           @"9886",
           @"9887",
           @"9888",
           @"9889",
           @"9890",
           @"9891",
           @"9892",
           @"9893",
           @"9894",
           @"9895",
           @"9896",
           @"9897",
           @"9898",
           @"9899",
           @"9900",
           @"9902",
           @"9903",
           @"9904",
           @"9905",
           @"9906",
           @"9907",
           @"9908",
           @"9909",
           @"9910",
           @"9911",
           @"9912",
           @"9913",
           @"9914",
           @"9915",
           @"9916",
           @"9917",
           @"9918",
           @"9919",
           @"9920",
           @"9921",
           @"9922",
           @"9923",
           @"9924",
           @"9925",
           @"9926",
           @"9927",
           @"9928",
           @"9929",
           @"9930",
           @"9931",
           @"9932",
           @"9933",
           @"9934",
           @"9935",
           @"9936",
           @"9938",
           @"9939",
           @"9940",
           @"9941",
           @"9942",
           @"9943",
           @"9944",
           @"9946",
           @"9948",
           @"9949",
           @"9950",
           @"9951",
           @"9952",
           @"9953",
           @"9954",
           @"9955",
           @"9956",
           @"9957",
           @"9958",
           @"9959",
           @"9960",
           @"9961",
           @"9962",
           @"9963",
           @"9964",
           @"9965",
           @"9966",
           @"9967",
           @"9968",
           @"9970",
           @"9971",
           @"9972",
           @"9973",
           @"9975",
           @"9978",
           @"9979",
           @"9980",
           @"9981",
           @"9982",
           @"9983",
           @"9984",
           @"9985",
           @"9986",
           @"9987",
           @"9988",
           @"9989",
           @"9990",
           @"9991",
           @"9994",
           @"9995",
           @"9996",
           @"9997",
           @"9998",
           @"9999",
           @"10001",
           @"10002",
           @"10003",
           @"10004",
           @"10005",
           @"10006",
           @"10007",
           @"10008",
           @"10009",
           @"10010",
           @"10011",
           @"10012",
           @"10013",
           @"10014",
           @"10015",
           @"10016",
           @"10017",
           @"10018",
           @"10019",
           @"10021",
           @"10022",
           @"10023",
           @"10024",
           @"10025",
           @"10026",
           @"10028",
           @"10029",
           @"10030",
           @"10031",
           @"10032",
           @"10033",
           @"10034",
           @"10035",
           @"10036",
           @"10037",
           @"10038",
           @"10039",
           @"10042",
           @"10043",
           @"10044",
           @"10045",
           @"10046",
           @"10047",
           @"10048",
           @"10050",
           @"10051",
           @"10052",
           @"10053",
           @"10054",
           @"10056",
           @"10057",
           @"10058",
           @"10060",
           @"10061",
           @"10062",
           @"10063",
           @"10065",
           @"10066",
           @"10067",
           @"10068",
           @"10069",
           @"10070",
           @"10071",
           @"10072",
           @"10073",
           @"10074",
           @"10075",
           @"10077",
           @"10078",
           @"10079",
           @"10080",
           @"10081",
           @"10082",
           @"10083",
           @"10084",
           @"10085",
           @"10086",
           @"10088",
           @"10089",
           @"10090",
           @"10091",
           @"10092",
           @"10093",
           @"10094",
           @"10095",
           @"10096",
           @"10097",
           @"10098",
           @"10099",
           @"10100",
           @"10101",
           @"10102",
           @"10103",
           @"10104",
           @"10105",
           @"10107",
           @"10108",
           @"10109",
           @"10110",
           @"10111",
           @"10112",
           @"10113",
           @"10114",
           @"10115",
           @"10116",
           @"10117",
           @"10118",
           @"10120",
           @"10121",
           @"10122",
           @"10124",
           @"10125",
           @"10126",
           @"10128",
           @"10129",
           @"10130",
           @"10131",
           @"10132",
           @"10133",
           @"10135",
           @"10137",
           @"10138",
           @"10139",
           @"10140",
           @"10141",
           @"10142",
           @"10143",
           @"10144",
           @"10145",
           @"10146",
           @"10147",
           @"10148",
           @"10149",
           @"10150",
           @"10151",
           @"10152",
           @"10153",
           @"10154",
           @"10155",
           @"10156",
           @"10157",
           @"10158",
           @"10160",
           @"10161",
           @"10162",
           @"10163",
           @"10164",
           @"10165",
           @"10166",
           @"10167",
           @"10168",
           @"10169",
           @"10170",
           @"10171",
           @"10172",
           @"10173",
           @"10174",
           @"10175",
           @"10176",
           @"10179",
           @"10180",
           @"10181",
           @"10182",
           @"10183",
           @"10184",
           @"10185",
           @"10186",
           @"10187",
           @"10188",
           @"10189",
           @"10190",
           @"10191",
           @"10193",
           @"10194",
           @"10196",
           @"10197",
           @"10198",
           @"10199",
           @"10200",
           @"10201",
           @"10202",
           @"10203",
           @"10204",
           @"10206",
           @"10207",
           @"10208",
           @"10209",
           @"10210",
           @"10212",
           @"10213",
           @"10214",
           @"10215",
           @"10216",
           @"10217",
           @"10218",
           @"10219",
           @"10220",
           @"10221",
           @"10222",
           @"10223",
           @"10224",
           @"10225",
           @"10226",
           @"10227",
           @"10228",
           @"10230",
           @"10231",
           @"10232",
           @"10233",
           @"10234",
           @"10235",
           @"10236",
           @"10237",
           @"10239",
           @"10240",
           @"10241",
           @"10242",
           @"10243",
           @"10244",
           @"10245",
           @"10246",
           @"10247",
           @"10248",
           @"10249",
           @"10250",
           @"10251",
           @"10252",
           @"10253",
           @"10254",
           @"10255",
           @"10256",
           @"10257",
           @"10258",
           @"10260",
           @"10261",
           @"10262",
           @"10263",
           @"10264",
           @"10265",
           @"10267",
           @"10268",
           @"10269",
           @"10270",
           @"10271",
           @"10272",
           @"10273",
           @"10274",
           @"10275",
           @"10276",
           @"10277",
           @"10278",
           @"10279",
           @"10280",
           @"10281",
           @"10282",
           @"10283",
           @"10284",
           @"10285",
           @"10287",
           @"10288",
           @"10289",
           @"10290",
           @"10291",
           @"10292",
           @"10293",
           @"10295",
           @"10296",
           @"10297",
           @"10298",
           @"10299",
           @"10300",
           @"10301",
           @"10303",
           @"10304",
           @"10306",
           @"10307",
           @"10308",
           @"10309",
           @"18737",
           @"39659",
           @"39672",
           @"39688",
           @"39735",
           @"39755",
           @"39764",
           @"39783",
           @"39784",
           @"39804",
           @"39819",
           @"39830",
           @"39883",
           @"39884",
           @"39899",
           @"39902",
           @"39906",
           @"39907",
           @"39923",
           @"39935",
           @"39953",
           @"39961",
           @"39962",
           @"41314",
           @"41315",
           @"41316",
           @"52010",
           @"62241",
           @"62249",
           @"62250",
           @"62255",
           @"62256",
           @"129",
           @"130",
           @"159",
           @"164",
           @"176",
           @"178",
           @"180",
           @"186",
           @"189",
           @"195",
           @"199",
           @"206",
           @"220",
           @"223",
           @"226",
           @"234",
           @"243",
           @"250",
           @"260",
           @"273",
           @"275",
           @"286",
           @"290",
           @"319",
           @"320",
           @"348",
           @"363",
           @"364",
           @"367",
           @"368",
           @"370",
           @"374",
           @"670",
           @"676",
           @"703",
           @"706",
           @"711",
           @"712",
           @"719",
           @"748",
           @"775",
           @"783",
           @"784",
           @"785",
           @"788",
           @"797",
           @"806",
           @"816",
           @"819",
           @"821",
           @"826",
           @"832",
           @"837",
           @"841",
           @"878",
           @"879",
           @"39978",
           @"39979",
           @"39980",
           @"39981",
           @"61923",
           @"61930",
           @"61931",
           @"61938",
           @"61940",
           @"76",
           @"126",
           @"132",
           @"141",
           @"193",
           @"210",
           @"215",
           @"224",
           @"232",
           @"233",
           @"251",
           @"257",
           @"263",
           @"271",
           @"274",
           @"277",
           @"281",
           @"292",
           @"293",
           @"295",
           @"296",
           @"304",
           @"305",
           @"321",
           @"353",
           @"355",
           @"362",
           @"369",
           @"372",
           @"668",
           @"674",
           @"681",
           @"709",
           @"724",
           @"731",
           @"735",
           @"743",
           @"746",
           @"749",
           @"753",
           @"758",
           @"763",
           @"768",
           @"770",
           @"790",
           @"795",
           @"799",
           @"803",
           @"808",
           @"827",
           @"833",
           @"840",
           @"843",
           @"846",
           @"850",
           @"854",
           @"858",
           @"863",
           @"5723",
           @"6309",
           @"6366",
           @"6380",
           @"12885",
           @"39987",
           @"39988",
           @"39989",
           @"61303",
           @"61924",
           @"61936",
           @"61937",
           @"61944",
           @"61945",
           @"61951",
           @"68246",
           @"998",
           @"999",
           @"1014",
           @"1036",
           @"1080",
           @"1098",
           @"1107",
           @"1112",
           @"1218",
           @"1231",
           @"1243",
           @"1700",
           @"1701",
           @"1703",
           @"1704",
           @"1707",
           @"1708",
           @"1710",
           @"1711",
           @"1713",
           @"1714",
           @"1717",
           @"1718",
           @"1719",
           @"1720",
           @"1722",
           @"1723",
           @"1725",
           @"1726",
           @"1728",
           @"1729",
           @"1730",
           @"1732",
           @"1734",
           @"1735",
           @"1736",
           @"1737",
           @"1738",
           @"1740",
           @"1741",
           @"1742",
           @"1743",
           @"1745",
           @"1746",
           @"1747",
           @"1748",
           @"1749",
           @"1750",
           @"1751",
           @"1753",
           @"1754",
           @"1755",
           @"1756",
           @"1757",
           @"1758",
           @"1760",
           @"1762",
           @"1763",
           @"1764",
           @"1765",
           @"1766",
           @"1767",
           @"1768",
           @"1769",
           @"1770",
           @"1771",
           @"1772",
           @"1773",
           @"1774",
           @"1775",
           @"1777",
           @"1778",
           @"1779",
           @"1780",
           @"1781",
           @"1782",
           @"1785",
           @"1786",
           @"1788",
           @"1789",
           @"1790",
           @"1791",
           @"1793",
           @"1794",
           @"1795",
           @"1796",
           @"1797",
           @"1798",
           @"1799",
           @"1800",
           @"1801",
           @"1804",
           @"1805",
           @"1806",
           @"1807",
           @"1808",
           @"1809",
           @"1810",
           @"1811",
           @"1812",
           @"1815",
           @"1816",
           @"1817",
           @"1819",
           @"1821",
           @"1822",
           @"1824",
           @"1825",
           @"1826",
           @"1827",
           @"1828",
           @"1830",
           @"1831",
           @"1833",
           @"1835",
           @"1836",
           @"1837",
           @"1838",
           @"1839",
           @"1840",
           @"1841",
           @"1842",
           @"1843",
           @"1844",
           @"1845",
           @"1846",
           @"1848",
           @"1849",
           @"1850",
           @"1851",
           @"1852",
           @"1853",
           @"1854",
           @"1855",
           @"1856",
           @"1857",
           @"1858",
           @"1859",
           @"1860",
           @"1862",
           @"1864",
           @"1865",
           @"1867",
           @"1868",
           @"1869",
           @"1870",
           @"1871",
           @"1872",
           @"1873",
           @"1874",
           @"1875",
           @"1876",
           @"1877",
           @"1878",
           @"1879",
           @"1880",
           @"1881",
           @"1883",
           @"1884",
           @"1886",
           @"1887",
           @"1889",
           @"1890",
           @"1891",
           @"1894",
           @"1895",
           @"1896",
           @"1897",
           @"1898",
           @"1899",
           @"1900",
           @"1901",
           @"1902",
           @"1903",
           @"1904",
           @"1905",
           @"1907",
           @"1908",
           @"1909",
           @"1910",
           @"1911",
           @"1912",
           @"1913",
           @"1914",
           @"1915",
           @"1916",
           @"1918",
           @"1921",
           @"1922",
           @"1923",
           @"1924",
           @"1925",
           @"1926",
           @"1927",
           @"1928",
           @"1929",
           @"1930",
           @"1931",
           @"1933",
           @"1934",
           @"1935",
           @"1936",
           @"1937",
           @"1939",
           @"1940",
           @"1941",
           @"1942",
           @"1943",
           @"1944",
           @"1947",
           @"1948",
           @"1949",
           @"1950",
           @"1951",
           @"1956",
           @"1958",
           @"1959",
           @"1960",
           @"1961",
           @"1962",
           @"1963",
           @"1964",
           @"1965",
           @"1966",
           @"1968",
           @"1970",
           @"1971",
           @"1972",
           @"1973",
           @"1974",
           @"1975",
           @"1976",
           @"1977",
           @"1978",
           @"1979",
           @"1980",
           @"1981",
           @"1982",
           @"1983",
           @"1984",
           @"1985",
           @"1987",
           @"1988",
           @"1989",
           @"1990",
           @"1991",
           @"1992",
           @"1993",
           @"1994",
           @"1995",
           @"1996",
           @"1997",
           @"1998",
           @"1999",
           @"2002",
           @"2003",
           @"2004",
           @"2005",
           @"2006",
           @"2009",
           @"2010",
           @"2011",
           @"2012",
           @"2016",
           @"2017",
           @"2019",
           @"2021",
           @"2023",
           @"2024",
           @"2026",
           @"2027",
           @"2028",
           @"2029",
           @"2030",
           @"2031",
           @"2032",
           @"2033",
           @"2035",
           @"2036",
           @"2038",
           @"2039",
           @"2042",
           @"2043",
           @"2044",
           @"2045",
           @"2046",
           @"2047",
           @"2048",
           @"2049",
           @"2050",
           @"2051",
           @"2052",
           @"2055",
           @"2058",
           @"2060",
           @"2061",
           @"2062",
           @"2063",
           @"2064",
           @"2065",
           @"2066",
           @"2067",
           @"2068",
           @"2069",
           @"2070",
           @"2071",
           @"2072",
           @"2075",
           @"2076",
           @"2077",
           @"2078",
           @"2080",
           @"2081",
           @"2082",
           @"2083",
           @"2084",
           @"2085",
           @"2086",
           @"2087",
           @"2088",
           @"2089",
           @"2092",
           @"2093",
           @"2094",
           @"2095",
           @"2096",
           @"2097",
           @"2100",
           @"2101",
           @"2102",
           @"2103",
           @"2104",
           @"2105",
           @"2106",
           @"2107",
           @"2108",
           @"2109",
           @"2110",
           @"2112",
           @"2113",
           @"2114",
           @"2115",
           @"2116",
           @"2118",
           @"2119",
           @"2121",
           @"2122",
           @"2123",
           @"2124",
           @"2125",
           @"2126",
           @"2127",
           @"2128",
           @"2129",
           @"2130",
           @"2131",
           @"2132",
           @"2134",
           @"2135",
           @"2136",
           @"2137",
           @"2139",
           @"2140",
           @"2141",
           @"2142",
           @"2143",
           @"2144",
           @"2145",
           @"2146",
           @"2147",
           @"2148",
           @"2149",
           @"2150",
           @"2151",
           @"2152",
           @"2154",
           @"2155",
           @"2156",
           @"2157",
           @"2159",
           @"2160",
           @"2161",
           @"2162",
           @"2163",
           @"2166",
           @"2167",
           @"2168",
           @"2169",
           @"2170",
           @"2171",
           @"2172",
           @"2173",
           @"2174",
           @"2175",
           @"2176",
           @"2177",
           @"2178",
           @"2180",
           @"2181",
           @"2182",
           @"2183",
           @"2185",
           @"2187",
           @"2188",
           @"2189",
           @"2190",
           @"2191",
           @"2192",
           @"2193",
           @"2195",
           @"2197",
           @"2198",
           @"2199",
           @"2200",
           @"2201",
           @"2202",
           @"2203",
           @"2204",
           @"2205",
           @"2207",
           @"2208",
           @"2209",
           @"2210",
           @"2211",
           @"2212",
           @"2213",
           @"2215",
           @"2216",
           @"2217",
           @"2218",
           @"2219",
           @"2220",
           @"2221",
           @"2222",
           @"2223",
           @"2224",
           @"2225",
           @"2226",
           @"2230",
           @"2231",
           @"2232",
           @"2233",
           @"2234",
           @"2235",
           @"2236",
           @"2237",
           @"2238",
           @"2239",
           @"2240",
           @"2241",
           @"2242",
           @"2243",
           @"2244",
           @"2245",
           @"2246",
           @"2247",
           @"2248",
           @"2250",
           @"2251",
           @"2254",
           @"2255",
           @"2257",
           @"2360",
           @"2362",
           @"2363",
           @"2365",
           @"2366",
           @"2367",
           @"2369",
           @"2372",
           @"2373",
           @"2374",
           @"2377",
           @"2378",
           @"2379",
           @"2380",
           @"2383",
           @"2385",
           @"2386",
           @"2387",
           @"2389",
           @"2390",
           @"2391",
           @"2392",
           @"2393",
           @"2394",
           @"2395",
           @"2396",
           @"2397",
           @"2398",
           @"2399",
           @"2402",
           @"2403",
           @"2404",
           @"2405",
           @"2406",
           @"2407",
           @"2408",
           @"2410",
           @"2411",
           @"2412",
           @"2413",
           @"2414",
           @"2415",
           @"2417",
           @"2419",
           @"2420",
           @"2421",
           @"2423",
           @"2424",
           @"2426",
           @"2427",
           @"2428",
           @"2429",
           @"2430",
           @"2431",
           @"2432",
           @"2433",
           @"2434",
           @"2435",
           @"2436",
           @"2438",
           @"2439",
           @"2440",
           @"2441",
           @"2442",
           @"2447",
           @"2448",
           @"2449",
           @"2450",
           @"2453",
           @"2454",
           @"2455",
           @"2456",
           @"2457",
           @"2458",
           @"2459",
           @"2460",
           @"2461",
           @"2463",
           @"2464",
           @"2465",
           @"2466",
           @"2468",
           @"2470",
           @"2471",
           @"2472",
           @"2473",
           @"2474",
           @"2475",
           @"2476",
           @"2477",
           @"2479",
           @"2481",
           @"2482",
           @"2483",
           @"2484",
           @"2485",
           @"2486",
           @"2487",
           @"2489",
           @"2490",
           @"2491",
           @"2492",
           @"2493",
           @"2494",
           @"2495",
           @"2496",
           @"2498",
           @"2499",
           @"2500",
           @"2501",
           @"2502",
           @"2504",
           @"2506",
           @"2507",
           @"2508",
           @"2509",
           @"2511",
           @"2513",
           @"2514",
           @"2515",
           @"2521",
           @"2522",
           @"2523",
           @"2524",
           @"2525",
           @"2526",
           @"2527",
           @"2528",
           @"2529",
           @"2530",
           @"2531",
           @"2532",
           @"2533",
           @"2536",
           @"3041",
           @"3042",
           @"10311",
           @"10312",
           @"10313",
           @"10315",
           @"10317",
           @"10318",
           @"10319",
           @"10322",
           @"10324",
           @"10326",
           @"10327",
           @"10328",
           @"10330",
           @"10333",
           @"10334",
           @"10335",
           @"10336",
           @"10337",
           @"10338",
           @"10339",
           @"10340",
           @"10341",
           @"10342",
           @"10343",
           @"10345",
           @"10346",
           @"10347",
           @"20413",
           @"39660",
           @"39666",
           @"39690",
           @"39698",
           @"39700",
           @"39706",
           @"39722",
           @"39727",
           @"39746",
           @"39763",
           @"39782",
           @"39805",
           @"39812",
           @"39815",
           @"39832",
           @"39834",
           @"39842",
           @"39857",
           @"39865",
           @"39866",
           @"39868",
           @"39869",
           @"39871",
           @"39898",
           @"39908",
           @"39912",
           @"39913",
           @"39917",
           @"39951",
           @"41928",
           @"44238",
           @"62266",
           @"62267",
           @"62269",
           @"62270",
           @"62271",
           @"62272",
           @"62273",
           @"62274",
           @"62276",
           @"62277",
           @"62278",
           @"62279",
           @"62280",
           @"62281",
           @"62282",
           @"62283",
           @"62284",
           @"62285",
           @"62286",
           @"62287",
           @"62288",
           @"62289",
           @"62290",
           @"62291",
           @"62292",
           @"62293",
           @"62294",
           @"62295",
           @"62296",
           @"62297",
           @"62299",
           @"62300",
           @"62302",
           @"62303",
           @"62305",
           @"62306",
           @"62308",
           @"62309",
           @"62310",
           @"62311",
           @"62312",
           @"62313",
           @"62314",
           @"62508",
           @"62509",
           @"63453",
           @"64923",
           @"64924",
           @"64925"
           ];
}


- (void)enrollEntireStudentDatabase {
  [self.statusLabel setText:@"Enrolling students to Kairos..."];
  
  NSDictionary *studentsDict = [NSDictionary dictionaryWithObjects:[self studentUserIDs] forKeys:[self studentNames]];
  
  __block int enrolledUsers = 0;
  
  for (NSString *studentName in studentsDict) {
    NSString *imageURL = [NSString stringWithFormat:@"http://moodle.ic.edu.lb/pluginfile.php/%@/user/icon/clean/f1?rev=1", studentsDict[studentName]];
    
    [KairosSDK enrollWithImageURL:imageURL subjectId:studentName galleryName:galleryIdentifier success:^(NSDictionary *response) {
      enrolledUsers++;
      NSLog(@"enrolled user succesfully %i", enrolledUsers);
      
      if (enrolledUsers == 1800) {
        [[NSUserDefaults standardUserDefaults] setBool:YES forKey:@"enrolledStudents"];
        [self.statusLabel setText:@"Enrolled all students to Kairos."];
        
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(2 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
          [self.statusLabel setText:@"Select a face by tapping above."];
        });
      }
      
    } failure:^(NSDictionary *response) {
      NSLog(@"failed to enroll user");
    }];
  }
}

#pragma mark - Picking an image
- (IBAction)scanNewFace {
  [self.statusLabel setText:@"User is selecting picture to recognize..."];
  
  //present the action sheet for picking a image
  UIActionSheet *as = [[UIActionSheet alloc] initWithTitle:@"Select Image Source" delegate:self cancelButtonTitle:@"Cancel" destructiveButtonTitle:nil otherButtonTitles:@"Camera", @"Library", nil];
  as.tag = 1;
  [as showInView:self.view];
}

- (void)actionSheet:(UIActionSheet *)actionSheet clickedButtonAtIndex:(NSInteger)buttonIndex {
  if (actionSheet.tag == 1) {//tag 1 is image picker action sheet
    if (buttonIndex == actionSheet.cancelButtonIndex) return;
    
    //set the source of the image picker to camera and present it
    imagePicker.sourceType = (buttonIndex == 0) ? UIImagePickerControllerSourceTypeCamera : UIImagePickerControllerSourceTypePhotoLibrary;
    if (imagePicker.sourceType == UIImagePickerControllerSourceTypeCamera) imagePicker.cameraDevice = UIImagePickerControllerCameraDeviceFront;
    
    [self presentViewController:imagePicker animated:YES completion:NULL];
  }
}

#pragma mark - UIImagePickerControllerDelegate
- (void)imagePickerControllerDidCancel:(UIImagePickerController *)picker {
  [picker dismissViewControllerAnimated:YES completion:NULL];//just dismiss the picker
}

- (void)imagePickerController:(UIImagePickerController *)picker didFinishPickingMediaWithInfo:(NSDictionary *)info {
  [self.statusLabel setText:@"Preparing faces for selection..."];
  
  //get edited image
  UIImage *selectedFace = [info objectForKey:UIImagePickerControllerEditedImage];
  
  //detect faces
  NSArray *faces = [selectedFace allFacesImagesWithAccuracy:CIDetectorAccuracyHigh];
  
  if (faces.count == 1) {
    [self recognizeFace:selectedFace];
    [picker dismissViewControllerAnimated:NO completion:NULL];
    
  } else {
    //present the collection VC so the user can choose which face he wants to recognize
    FaceSelectionCollectionViewController *collectionVC = [[UIStoryboard storyboardWithName:@"Main" bundle:[NSBundle mainBundle]] instantiateViewControllerWithIdentifier:@"faceSelectionVC"];
    collectionVC.faces = faces;
    collectionVC.viewController = self;
    
    //dismiss the picker
    [picker dismissViewControllerAnimated:NO completion:^{
      [self presentViewController:collectionVC animated:YES completion:NULL];
    }];
  }
}

#pragma mark - Status Bar
- (BOOL)prefersStatusBarHidden {return NO;}
- (UIStatusBarStyle)preferredStatusBarStyle{return UIStatusBarStyleLightContent;}

@end
